### ISSUE TITLE
How to convert mat to lmdb with your code?

### ISSUE THREAD

**Issue by tzczsq** [uchicago-cs/deepdish#12]
Hi, please tell me how to convert mat data to lmdb for caffe use/

**Comment by gustavla** [comment]
Old Matlab files can be read by `scipy.io.loadmat`, and new Matlab files are simply HDF5 files and can be read using `deepdish.io.load`. For saving to lmdb, you can just follow the tutorial on the blog: http://deepdish.io/2015/04/28/creating-lmdb-in-python/
