### ISSUE TITLE
`save` function with mode 'a'

### ISSUE THREAD

**Issue by gaow** [uchicago-cs/deepdish#14]
Currently `dd.io.save` overwrites target file if exists. Would it be a good idea to add a `mode` argument so that the target file can be constantly updated as new data arrives?

**Comment by gustavla** [comment]
Can you describe how new data arrives? You mean new groups or is it an array that grows?

Would it have semantics similar to `d1.update(d2)`, if `d1` and `d2` are dictionaries and `d1` represents the already saved file and `d2` the new?

**Comment by gaow** [comment]
I meant new groups for my application. I work with data that contains many groups, too many to keep in RAM all at once and my computational routine analyzes one batch of groups at a time and write to file. Ideally all groups can be written to the same file if there is a `a`. model. Thanks a lot!

**Comment by gustavla** [comment]
It's a good idea and I will keep it in mind. I would also welcome a PR with a more concrete suggestion if you or anyone else want to contribute.
