### ISSUE TITLE
A Mistake?  

### ISSUE THREAD

**Issue by ArEnSc** [uchicago-cs/deepdish#17]
http://deepdish.io/2014/10/28/hintons-dark-knowledge/

I was wondering if this was a mistake
Hinton in his lecture slides says that raising the temperature was

yk/T

where as you have it as

yk^1/T

which is a squareroot ? if I use T ?

Can you explain ? 
this occurs for the denominator as well.

**Comment by ArEnSc** [comment]
http://www.ttic.edu/dl/dark14.pdf
slide 6

**Comment by gustavla** [comment]
In Hinton's slides, z is a score vector and to get a distribution over labels, you take y = softmax(z). In my blog post, y the distribution vector, not the score vector.

So, to change the temperature of z, you simply divide by T - no arguments there. However, to change the temperature when you already have y, you have take it to the power of 1/T and then re-normalize.

It follows from the fact that exp(z/T) = exp(z)^(1/T). Makes sense?

**Comment by ArEnSc** [comment]
are there any papers on this topic ?

**Comment by ArEnSc** [comment]
thanks!
