### ISSUE TITLE
Error while installing deepdish

### ISSUE THREAD

**Issue by pras005** [uchicago-cs/deepdish#2]
I'm trying to create an LMDB database file to be used with Caffe according to [this](http://deepdish.io/) tutorial on an Ubuntu 14.04 machine using Anaconda Python 2.7.9. However, when I do `pip install deepdish`, I'm getting the following error:

    Collecting deepdish
      Using cached deepdish-0.1.4.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "/tmp/pip-build-qKwOBx/deepdish/setup.py", line 12, in <module>
            with open('requirements.txt') as f:
        IOError: [Errno 2] No such file or directory: 'requirements.txt'
    
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-qKwOBx/deepdish

Any ideas why this error might be occurring and how to go about correcting it? Any help is much appreciated. Thank you.

**Comment by pras005** [comment]
Can't seem to figure out why the error occurred, but after struggling for a while, I did the following and it seemed to work:

 1. Download the zip file from Github. 
 2. Unzip the file after navigating to the directory where you've downloaded the file using the command `unzip deepdish-master.zip`.
 3. Navigate to the unzipped folder: `cd deepdish-master`.
 4. Make the setup.py file executable: `chmod +x setup.py`.
 5. Run the file with the 'install' option: `./setup.py install`.
 6. If you want, you may delete the zip folder and the unzipped folder.

Now if you go into the python environment in the terminal and do `import deepdish as dd`, it works like a charm!

**Comment by Shaunakde** [comment]
Hey, I did the download compile cycle too. pip install fails for some
strange reason. Il post my pip error logs from work.

SD

On Tue, Jun 16, 2015 at 1:15 AM, Prasanna Date <notifications@github.com>
wrote:

> Can't seem to figure out why the error occurred, but after struggling for
> a while, I did the following and it seemed to work:
>
>    1. Download the zip file from Github.
>    2. Unzip the file after navigating to the directory where you've
>    downloaded the file using the command unzip deepdish-master.zip.
>    3. Navigate to the unzipped folder: cd deepdish-master.
>    4. Make the setup.py file executable: chmod +x setup.py.
>    5. Run the file with the 'install' option: ./setup.py install.
>    6. If you want, you may delete the zip folder and the unzipped folder.
>
> Now if you go into the python environment in the terminal and do import
> deepdish as dd, it works like a charm!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uchicago-cs/deepdish/issues/2#issuecomment-112185391>.
>



-- 
Shaunak De
http://shaunak.de/

**Comment by gustavla** [comment]
Thanks for noticing this! I just uploaded a new version to PyPI resolving this problem (fixed in 396c20ca6e51cc0a56bbc3a6580969858a4b4f9b), so `pip install deepdish` should now work (make sure you have cython and numpy first though). If it still doesn't work, let me know and I'll re-open this issue.
