### ISSUE TITLE
Hanging file refs if exception occurs during hdf5io.load/hdf5io.save 

### ISSUE THREAD

**Issue by ranr01** [uchicago-cs/deepdish#3]
Hey,

Thanks for the hdf5io module. It's really great and easy to use.
One issue I encountered while using it is that if an error occurs during save/load the file is left opened and cannot be reopened.

I solved this by simply putting the open file operation with in a context manager i.e:

```
with  tables.open_file(path, mode='w') as h5file:
    #do stuff
```    

This way the file is always closed when the function returns.

Thanks again for the module. Really useful.

Cheers,
Ran

**Comment by gustavla** [comment]
I definitely agree with that. If you want to open up a PR that implements that, I'll merge it. If not, I'll just add it myself tonight. Thanks!

**Comment by ranr01** [comment]
Hmm.. I'll try the PR. I'm not very experienced with Github so it will be a good way to practice...
