### ISSUE TITLE
optional dependencies?

### ISSUE THREAD

**Issue by mheilman** [uchicago-cs/deepdish#7]
The package currently depends on `matplotlib` and `skimage`.  These are both pretty hefty dependencies, and they don't appear to be necessary for the core functionality.  Maybe it'd be worth making them optional (e.g., like here in `statsmodels`:  https://github.com/statsmodels/statsmodels/blob/4b55fa4871cf3f1dbd2e30bfe00d80df87d4b340/statsmodels/graphics/utils.py#L9).

**Comment by gustavla** [comment]
Thanks for poining this out, @mheilman! Actually, the matplotlib one is a relic and should be taken out entirely. I agree that the scikit-image one should be made optional.

I'll do after this weekend unless of course I see a PR come in ;)

**Comment by mheilman** [comment]
just a thought I had when installing it.  I'd have just made a PR but wasn't sure exactly why those dependencies were there.
